language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack-dev libblas-dev gfortran
  
# command to install dependencies
install:
  - pip install .
  - travis_wait pip install -r requirements.txt
  
script: python crrlpy/crrls.py
script: python crrlpy/models/rrlmod.py
